/**
 * Entity Schemas & Field Definitions for ERP Bulk Importer
 * Aligned with Supabase PostgreSQL schema: public.courses, public.batches, public.students, public.parents
 */

export const ENTITY_SCHEMAS = {
  courses: {
    id: 'courses',
    title: 'Courses & Academic Streams',
    table: 'courses',
    primaryKey: 'id',
    uniqueKey: 'code',
    order: 1,
    description: 'Academic degrees and streams (e.g., 11th Science, FY-BCA, TY-BCA)',
    fields: [
      {
        name: 'code',
        label: 'Course Code',
        type: 'string',
        required: true,
        description: 'Unique course code (e.g., 11TH-SCI, FY-BCA)',
        aliases: ['course_code', 'course code', 'code', 'stream code', 'course id', 'id'],
        sample: 'FY-BCA',
      },
      {
        name: 'name',
        label: 'Course Name',
        type: 'string',
        required: true,
        description: 'Official academic stream title',
        aliases: ['name', 'course_name', 'course name', 'title', 'course title', 'stream name'],
        sample: 'First Year — Bachelor of Computer Applications',
      },
      {
        name: 'level',
        label: 'Academic Level',
        type: 'enum',
        required: true,
        options: ['11th', '12th', 'FY', 'SY', 'TY', 'BCA', 'Other'],
        description: 'Standard academic level',
        aliases: ['level', 'course_level', 'academic level', 'year', 'standard', 'grade'],
        sample: 'FY',
      },
      {
        name: 'description',
        label: 'Description',
        type: 'string',
        required: false,
        description: 'Optional stream overview or curriculum notes',
        aliases: ['description', 'desc', 'notes', 'details'],
        sample: 'Undergraduate Computer Applications (Sem I & II)',
      },
      {
        name: 'is_active',
        label: 'Active Status',
        type: 'boolean',
        required: false,
        default: true,
        description: 'Whether course is active (true/false, Yes/No, 1/0)',
        aliases: ['is_active', 'active', 'status'],
        sample: 'TRUE',
      },
    ],
  },

  batches: {
    id: 'batches',
    title: 'Batches & Cohorts',
    table: 'batches',
    primaryKey: 'id',
    uniqueKey: 'code',
    order: 2,
    dependencies: ['courses'],
    description: 'Class divisions and cohorts mapped to courses (requires Courses to be imported first)',
    fields: [
      {
        name: 'code',
        label: 'Batch Code',
        type: 'string',
        required: true,
        description: 'Unique batch identifier (e.g., FYBCA-A, 11SCI-S1)',
        aliases: ['batch_code', 'batch code', 'code', 'division code', 'batch id', 'id'],
        sample: 'FYBCA-A',
      },
      {
        name: 'name',
        label: 'Batch Name',
        type: 'string',
        required: true,
        description: 'Descriptive title of the cohort',
        aliases: ['batch_name', 'batch name', 'name', 'title', 'cohort name'],
        sample: 'FYBCA Division A (Morning Shift)',
      },
      {
        name: 'course_code',
        label: 'Course Code',
        type: 'string',
        required: true,
        description: 'Exact course code (e.g. 11TH-SCI, FY-BCA) or UUID in public.courses',
        aliases: [
          'course_code',
          'course code',
          'course',
          'course name',
          'course_name',
          'stream',
          'stream code',
          'course_id',
          'course id',
          'course code (foreign key)',
          'course code / id',
        ],
        sample: 'FY-BCA',
      },
      {
        name: 'academic_year',
        label: 'Academic Year',
        type: 'string',
        required: false,
        default: '2026-27',
        description: 'Academic session (e.g., 2026-27)',
        aliases: ['academic_year', 'academic year', 'ay', 'session', 'year'],
        sample: '2026-27',
      },
      {
        name: 'shift',
        label: 'Shift',
        type: 'string',
        required: false,
        default: 'Morning',
        description: 'Morning, Afternoon, or Evening',
        aliases: ['shift', 'batch shift', 'timing shift', 'session shift'],
        sample: 'Morning',
      },
      {
        name: 'timing',
        label: 'Timing / Schedule',
        type: 'string',
        required: false,
        description: 'Class session hours (e.g., 07:30 AM – 10:30 AM)',
        aliases: ['timing', 'time', 'schedule', 'hours', 'session time'],
        sample: '07:30 AM – 10:30 AM',
      },
      {
        name: 'classroom',
        label: 'Classroom / Hall',
        type: 'string',
        required: false,
        description: 'Assigned lecture room or laboratory (e.g., Room 101, LH-1)',
        aliases: ['classroom', 'room', 'room no', 'hall', 'venue', 'lab'],
        sample: 'Lecture Hall 101',
      },
      {
        name: 'max_capacity',
        label: 'Maximum Capacity',
        type: 'number',
        required: false,
        default: 60,
        description: 'Maximum student enrollment limit (must be > 0)',
        aliases: ['max_capacity', 'capacity', 'intake', 'seats', 'max students', 'limit'],
        sample: 60,
      },
      {
        name: 'is_active',
        label: 'Active Status',
        type: 'boolean',
        required: false,
        default: true,
        description: 'Whether batch is active (true/false, Yes/No)',
        aliases: ['is_active', 'active', 'status'],
        sample: 'TRUE',
      },
    ],
  },

  students: {
    id: 'students',
    title: 'Students Directory',
    table: 'students',
    primaryKey: 'id',
    uniqueKey: 'admission_no',
    order: 3,
    dependencies: ['batches'],
    description: 'Enrolled students linked to Batches and Courses (requires Batches to be imported first)',
    fields: [
      {
        name: 'admission_no',
        label: 'Admission Number',
        type: 'string',
        required: true,
        description: 'Unique student admission ID (e.g., ADM-2026-001)',
        aliases: ['admission_no', 'admission number', 'admission no', 'adm no', 'student id', 'id', 'enrollment no', 'registration no'],
        sample: 'ADM-2026-001',
      },
      {
        name: 'full_name',
        label: 'Student Full Name',
        type: 'string',
        required: true,
        description: 'Full official name of the student',
        aliases: ['full_name', 'name', 'student name', 'full name', 'student', 'candidate name'],
        sample: 'Aarav Sharma',
      },
      {
        name: 'batch_code',
        label: 'Batch Code',
        type: 'string',
        required: true,
        description: 'Code of the assigned batch in public.batches (e.g., FYBCA-A)',
        aliases: [
          'batch_code',
          'batch code',
          'batch',
          'division',
          'section',
          'class',
          'batch code (foreign key)',
        ],
        sample: 'FYBCA-A',
      },
      {
        name: 'course_code',
        label: 'Course Code',
        type: 'string',
        required: false,
        description: 'Optional course code (auto-derived from batch if omitted)',
        aliases: [
          'course_code',
          'course code',
          'course',
          'stream',
          'course code (optional)',
          'course name',
        ],
        sample: 'FY-BCA',
      },
      {
        name: 'roll_no',
        label: 'Roll Number',
        type: 'string',
        required: false,
        description: 'Class roll call number',
        aliases: ['roll_no', 'roll no', 'roll number', 'roll', 'class roll', 'class_roll', 'roll_number'],
        sample: '101',
      },
      {
        name: 'gender',
        label: 'Gender',
        type: 'enum',
        required: false,
        options: ['Male', 'Female', 'Other'],
        description: 'Male, Female, or Other',
        aliases: ['gender', 'sex'],
        sample: 'Male',
      },
      {
        name: 'dob',
        label: 'Date of Birth',
        type: 'date',
        required: false,
        description: 'Format: YYYY-MM-DD (e.g., 2008-05-15)',
        aliases: ['dob', 'date of birth', 'birth date', 'birthdate'],
        sample: '2008-05-15',
      },
      {
        name: 'phone',
        label: 'Student Phone',
        type: 'string',
        required: false,
        description: 'Student contact number',
        aliases: ['phone', 'mobile', 'contact', 'student phone', 'student mobile', 'cell'],
        sample: '9876543210',
      },
      {
        name: 'email',
        label: 'Student Email',
        type: 'email',
        required: false,
        description: 'Student email address',
        aliases: ['email', 'student email', 'mail', 'email address'],
        sample: 'aarav.sharma@example.com',
      },
      {
        name: 'blood_group',
        label: 'Blood Group',
        type: 'string',
        required: false,
        description: 'e.g., O+, A+, B+, AB+, O-',
        aliases: ['blood_group', 'blood group', 'blood', 'bg'],
        sample: 'O+',
      },
      {
        name: 'address',
        label: 'Residential Address',
        type: 'string',
        required: false,
        description: 'Home address / locality',
        aliases: ['address', 'residence', 'residential address', 'location', 'city'],
        sample: 'Flat 402, Sunshine Heights, Mumbai',
      },
      {
        name: 'enrollment_date',
        label: 'Enrollment Date',
        type: 'date',
        required: false,
        default: new Date().toISOString().split('T')[0],
        description: 'Date admitted (YYYY-MM-DD)',
        aliases: ['enrollment_date', 'enrollment date', 'admission date', 'joining date', 'date of admission'],
        sample: '2026-06-15',
      },
      {
        name: 'status',
        label: 'Enrollment Status',
        type: 'enum',
        required: false,
        default: 'active',
        options: ['active', 'inactive', 'suspended', 'graduated'],
        description: 'active, inactive, suspended, or graduated',
        aliases: ['status', 'enrollment status', 'academic status'],
        sample: 'active',
      },
    ],
  },

  parents: {
    id: 'parents',
    title: 'Parents & Guardians',
    table: 'parents',
    primaryKey: 'id',
    uniqueKey: 'phone_and_student',
    order: 4,
    dependencies: ['students'],
    description: 'Guardians linked to student wards for alerts (requires Students to be imported first)',
    fields: [
      {
        name: 'full_name',
        label: 'Guardian Full Name',
        type: 'string',
        required: true,
        description: 'Full name of parent or legal guardian',
        aliases: ['full_name', 'guardian name', 'parent name', 'name', 'father name', 'mother name', 'guardian'],
        sample: 'Rajesh Sharma',
      },
      {
        name: 'phone',
        label: 'Guardian Phone',
        type: 'string',
        required: true,
        description: 'Primary contact mobile number for roll call notices',
        aliases: ['phone', 'mobile', 'contact', 'parent phone', 'parent mobile', 'guardian phone', 'guardian mobile'],
        sample: '9822012345',
      },
      {
        name: 'student_admission_no',
        label: 'Student Admission Number (Ward)',
        type: 'string',
        required: true,
        description: 'Admission number of the student ward in public.students (e.g., ADM-2026-001)',
        aliases: ['student_admission_no', 'student admission no', 'student admission number', 'admission no', 'student id', 'ward admission no', 'ward id'],
        sample: 'ADM-2026-001',
      },
      {
        name: 'relationship',
        label: 'Relationship to Student',
        type: 'string',
        required: false,
        default: 'Father',
        description: 'Father, Mother, or Guardian',
        aliases: ['relationship', 'relation', 'relationship type', 'relation to student'],
        sample: 'Father',
      },
      {
        name: 'email',
        label: 'Guardian Email',
        type: 'email',
        required: false,
        description: 'Email for fee receipts and notices',
        aliases: ['email', 'parent email', 'guardian email', 'mail'],
        sample: 'rajesh.sharma@example.com',
      },
      {
        name: 'preferred_notification_channel',
        label: 'Notification Channel',
        type: 'enum',
        required: false,
        default: 'telegram',
        options: ['telegram', 'sms', 'whatsapp', 'email'],
        description: 'Preferred alert channel (telegram, sms, whatsapp, email)',
        aliases: ['preferred_notification_channel', 'channel', 'notification channel', 'preferred channel', 'alert channel'],
        sample: 'telegram',
      },
      {
        name: 'telegram_chat_id',
        label: 'Telegram Chat ID (Private)',
        type: 'string',
        required: false,
        description: 'Private telegram numeric chat identifier if known',
        aliases: ['telegram_chat_id', 'telegram id', 'chat id', 'telegram chat id', 'chat_id'],
        sample: '',
      },
      {
        name: 'is_primary_contact',
        label: 'Primary Emergency Contact',
        type: 'boolean',
        required: false,
        default: true,
        description: 'Whether guardian is primary emergency contact (true/false, Yes/No)',
        aliases: ['is_primary_contact', 'primary contact', 'is primary', 'primary'],
        sample: 'TRUE',
      },
    ],
  },
};

/**
 * Returns list of supported entities in recommended import sequence
 */
export const RECOMMENDED_IMPORT_SEQUENCE = [
  ENTITY_SCHEMAS.courses,
  ENTITY_SCHEMAS.batches,
  ENTITY_SCHEMAS.students,
  ENTITY_SCHEMAS.parents,
];
